# Generated by Django 3.1.13 on 2021-11-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('birth', models.DateField()),
                ('cpf', models.CharField(max_length=20)),
                ('interests', models.CharField(max_length=150)),
                ('state', models.CharField(choices=[('MG', 'Minas Gerais'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('BA', 'Bahia'), ('DF', 'Distrito Federal')], max_length=2)),
            ],
        ),
    ]
